*** /opt/git-fs/Makefile	2021-04-07 13:20:20.852783290 -0400
--- gitfs-Makefile	2021-11-30 18:13:27.893566129 -0500
***************
*** 2,8 ****
  OPTS=-rdynamic -O2 -Wall -lfuse -lgit2
  
  git-fs: clean
! 	gcc ${OPTS} -o git-fs git-fs.c
  
  example: git-fs
  	test -d test-mount || mkdir test-mount
--- 2,8 ----
  OPTS=-rdynamic -O2 -Wall -lfuse -lgit2
  
  git-fs: clean
! 	gcc -o git-fs git-fs.c ${OPTS}
  
  example: git-fs
  	test -d test-mount || mkdir test-mount
